<ADSWorkspace Revision="106" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="diploma_barchelor_lib_lay.prf" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="diploma_barchelor_lib" />
        <ConfigFile Name="dds.cfg" />
        <Dataset Name="BPF_test.ds" />
        <Data_Files Name="BPF_test.ds" />
        <Data_Files Name="BPF_test_data\logFile.txt" />
        <Dataset Name="SPF5043Z.ds" />
        <Data_Files Name="SPF5043Z.ds" />
        <Data_Files Name="SPF5043Z_data\logFile.txt" />
        <Data_Files Name="S_Params\SPF-5043_DeEmbed_W60_D8_5V_preliminary.s2p" />
        <Preferences Name="ads_builtin_lay.prf" />
        <Preferences Name="ads_datacmps_lay.prf" />
        <Preferences Name="ads_rflib_lay.prf" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Preferences Name="diploma_barchelor_lib_sch.prf" />
        <Dataset Name="SPF5043Z_SCH.ds" />
        <Data_Files Name="SPF5043Z_SCH.ds" />
        <Data_Files Name="SPF5043Z_SCH_data\logFile.txt" />
        <Dataset Name="BPF_IN2.ds" />
        <Data_Files Name="BPF_IN2.ds" />
        <Data_Files Name="BPF_IN2_data\logFile.txt" />
        <Dataset Name="Test_sch.ds" />
        <Data_Files Name="Test_sch.ds" />
        <Data_Files Name="Test_sch_data\logFile.txt" />
        <Folder Name="Elements">
            <Cell Name="diploma_barchelor_lib:FP3P7-814-10" />
            <Cell Name="diploma_barchelor_lib:SPF5043Z" />
            <Cell Name="diploma_barchelor_lib:BalUn JT" />
            <Cell Name="diploma_barchelor_lib:SX1257" />
            <Cell Name="diploma_barchelor_lib:RFPA0133" />
            <Cell Name="diploma_barchelor_lib:LPF868" />
        </Folder>
        <Dataset Name="AAA.ds" />
        <Dataset Name="AAAA2_MomUW.ds" />
        <Dataset Name="AAAA2_MomUW_a.ds" />
        <Dataset Name="AAAA_MomUW.ds" />
        <Dataset Name="AAAA_MomUW_a.ds" />
        <Data_Files Name="AAA.ds" />
        <Data_Files Name="AAAA2_MomUW.ds" />
        <Data_Files Name="AAAA2_MomUW_a.ds" />
        <Data_Files Name="AAAA_MomUW.ds" />
        <Data_Files Name="AAAA_MomUW_a.ds" />
        <Data_Files Name="AAA_data\logFile.txt" />
        <Folder Name="Test Circuits">
            <Cell Name="diploma_barchelor_lib:TEST_C2" />
            <Data_Display Name="TEST_C2.dds" />
            <Cell Name="diploma_barchelor_lib:TEST_C1" />
        </Folder>
        <Dataset Name="SPF5043Z_SCH_CPWG.ds" />
        <Data_Files Name="SPF5043Z_SCH_CPWG.ds" />
        <Data_Files Name="SPF5043Z_SCH_CPWG_data\logFile.txt" />
        <Substrate Name="diploma_barchelor_lib:tech.subst" />
        <Dataset Name="AAA_MomUW.ds" />
        <Data_Files Name="AAA_MomUW.ds" />
        <Dataset Name="AAA_MomUW_a.ds" />
        <Data_Files Name="AAA_MomUW_a.ds" />
        <Dataset Name="BPF_IN2_TOPOLOGY.ds" />
        <Data_Files Name="BPF_IN2_TOPOLOGY.ds" />
        <Data_Files Name="BPF_IN2_TOPOLOGY_data\logFile.txt" />
        <Dataset Name="FP3P7_814_10_LINE_MomUW.ds" />
        <Data_Files Name="FP3P7_814_10_LINE_MomUW.ds" />
        <Dataset Name="FP3P7_814_10_LINE_MomUW_a.ds" />
        <Data_Files Name="FP3P7_814_10_LINE_MomUW_a.ds" />
        <Dataset Name="SPF5043Z_LINE_MomUW.ds" />
        <Data_Files Name="SPF5043Z_LINE_MomUW.ds" />
        <Dataset Name="SPF5043Z_LINE_MomUW_a.ds" />
        <Data_Files Name="SPF5043Z_LINE_MomUW_a.ds" />
        <Dataset Name="SPF5043Z_TOPOLOGY.ds" />
        <Data_Files Name="SPF5043Z_TOPOLOGY.ds" />
        <Data_Files Name="SPF5043Z_TOPOLOGY_data\logFile.txt" />
        <Dataset Name="TEST_C1.ds" />
        <Data_Files Name="TEST_C1.ds" />
        <Data_Files Name="TEST_C1_data\logFile.txt" />
        <Dataset Name="BPF_IN1.ds" />
        <Data_Files Name="BPF_IN1.ds" />
        <Data_Files Name="BPF_IN1_data\logFile.txt" />
        <Dataset Name="FP3P7_814_10_LINE_IN2_MomUW.ds" />
        <Dataset Name="FP3P7_814_10_LINE_IN1_MomUW.ds" />
        <Data_Files Name="FP3P7_814_10_LINE_IN1_MomUW.ds" />
        <Dataset Name="BPF_IN1_TOPOLOGY.ds" />
        <Data_Files Name="BPF_IN1_TOPOLOGY.ds" />
        <Data_Files Name="BPF_IN1_TOPOLOGY_data\logFile.txt" />
        <Folder Name="Input Circuit">
            <Folder Name="AMP IN">
                <Cell Name="diploma_barchelor_lib:SPF5043Z_SCH_CPWG" />
                <Data_Display Name="SPF5043Z_SCH_CPWG.dds" />
                <Cell Name="diploma_barchelor_lib:SPF5043Z_TOPOLOGY" />
                <Cell Name="diploma_barchelor_lib:SPF5043Z_LINE" />
                <Data_Display Name="SPF5043Z_TOPOLOGY.dds" />
            </Folder>
            <Folder Name="BPF IN1">
                <Cell Name="diploma_barchelor_lib:BPF IN1" />
                <Cell Name="diploma_barchelor_lib:FP3P7-814-10 LINE IN1" />
                <Cell Name="diploma_barchelor_lib:BPF IN1 TOPOLOGY" />
                <Data_Display Name="BPF IN1.dds" />
                <Data_Display Name="BPF IN1 TOPOLOGY.dds" />
            </Folder>
            <Folder Name="BPF IN2">
                <Cell Name="diploma_barchelor_lib:BPF IN2" />
                <Data_Display Name="BPF IN2.dds" />
                <Cell Name="diploma_barchelor_lib:BPF IN2 TOPOLOGY" />
                <Data_Display Name="BPF IN2 TOPOLOGY.dds" />
                <Data_Display Name="FP3P7-814-10 LINE.dds" />
                <Cell Name="diploma_barchelor_lib:FP3P7-814-10 LINE IN2" />
            </Folder>
            <Cell Name="diploma_barchelor_lib:INPL" />
            <Data_Display Name="INPL.dds" />
            <Folder Name="coupler">
                <Cell Name="diploma_barchelor_lib:coupler" />
                <Data_Display Name="coupler.dds" />
                <Cell Name="diploma_barchelor_lib:coupler_em" />
                <Cell Name="diploma_barchelor_lib:coupler_line" />
                <Data_Display Name="coupler_line.dds" />
            </Folder>
        </Folder>
        <Folder Name="Output Circuit">
            <Folder Name="BALUN+BPF">
                <Cell Name="diploma_barchelor_lib:BALUN+BPF_SCH" />
                <Data_Display Name="BALUN+BPF_SCH.dds" />
                <Cell Name="diploma_barchelor_lib:BALUN + BPF Line" />
                <Cell Name="diploma_barchelor_lib:BALUN+BPF_TOPOLOGY" />
                <Data_Display Name="BALUN+BPF_TOPOLOGY.dds" />
            </Folder>
            <Folder Name="PA">
                <Cell Name="diploma_barchelor_lib:PA_SCH" />
                <Data_Display Name="PA_SCH.dds" />
            </Folder>
            <Folder Name="LPF out">
                <Cell Name="diploma_barchelor_lib:LPF_SCH" />
                <Data_Display Name="LPF_SCH.dds" />
            </Folder>
            <Cell Name="diploma_barchelor_lib:OPL" />
            <Data_Display Name="OPL.dds" />
        </Folder>
        <Dataset Name="INPL.ds" />
        <Data_Files Name="INPL.ds" />
        <Data_Files Name="INPL_data\logFile.txt" />
        <Dataset Name="BALUN_SCH.ds" />
        <Data_Files Name="BALUN_SCH.ds" />
        <Data_Files Name="BALUN_SCH_data\logFile.txt" />
        <Data_Files Name="S_Params\balun.s3p" />
        <Preferences Name="ads_simulation_lay.prf" />
        <Log Name="search_history.log" />
        <Log Name="netlist.log" />
        <Log Name="readegs.log" />
        <Dataset Name="BALUN___BPF_Line_MomUW.ds" />
        <Data_Files Name="BALUN___BPF_Line_MomUW.ds" />
        <Dataset Name="BALUN_BPF_TOPOLOGY.ds" />
        <Data_Files Name="BALUN_BPF_TOPOLOGY.ds" />
        <Data_Files Name="BALUN_BPF_TOPOLOGY_data\logFile.txt" />
        <Dataset Name="PA_SCH.ds" />
        <Data_Files Name="PA_SCH.ds" />
        <Data_Files Name="PA_SCH_data\logFile.txt" />
        <Data_Files Name="dc_annotation\diploma_barchelor_lib_%P%A_%S%C%H_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\diploma_barchelor_lib_%P%A_%S%C%H_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\diploma_barchelor_lib_%T%E%S%T_%C1_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\diploma_barchelor_lib_%T%E%S%T_%C1_schematic\annotation_map.xml" />
        <Data_Files Name="S_Params\BPF bigrange.s2p" />
        <Data_Files Name="S_Params\BPF.s2p" />
        <Data_Files Name="S_Params\LPF.s2p" />
        <Dataset Name="LPF_SCH.ds" />
        <Data_Files Name="LPF_SCH.ds" />
        <Data_Files Name="LPF_SCH_data\logFile.txt" />
        <Dataset Name="OPL.ds" />
        <Data_Files Name="dc_annotation\diploma_barchelor_lib_%O%P%L_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\diploma_barchelor_lib_%O%P%L_schematic\annotation_map.xml" />
        <Data_Files Name="OPL.ds" />
        <Data_Files Name="OPL_data\logFile.txt" />
        <Log Name="readdxf.log" />
        <Preferences Name="ads_behavioral_lay.prf" />
        <Library Name="ads_verification_test_bench" />
        <Dataset Name="coupler.ds" />
        <Data_Files Name="coupler.ds" />
        <Data_Files Name="coupler_data\logFile.txt" />
        <Dataset Name="coupler_MomUW.ds" />
        <Data_Files Name="coupler_MomUW.ds" />
        <Dataset Name="coupler_em_MomUW.ds" />
        <Data_Files Name="coupler_em_MomUW.ds" />
        <Log Name="writedxf.log" />
        <Dataset Name="coupler_em_MomUW_a.ds" />
        <Dataset Name="coupler_line.ds" />
        <Dataset Name="TEST_C2.ds" />
        <Data_Files Name="coupler_em_MomUW_a.ds" />
        <Data_Files Name="coupler_line.ds" />
        <Data_Files Name="coupler_line_data\logFile.txt" />
        <Data_Files Name="dc_annotation\diploma_barchelor_lib_%T%E%S%T_%C2_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\diploma_barchelor_lib_%T%E%S%T_%C2_schematic\annotation_map.xml" />
        <Data_Files Name="TEST_C2.ds" />
        <Data_Files Name="TEST_C2_data\logFile.txt" />
    </Workspace>
</ADSWorkspace>
